name: portfolio
description: deandreamatias
version: 2.2.0
code: 17

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2
  unicons: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies: 
  flutter_lints: ^6.0.0

flutter:
  generate: true